//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15pl04.Ucc.Commons.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_15pl04.Ucc.Commons.Tests.XmlMessages", typeof(XmlMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;DivideProblem xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///               xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///               xsi:noNamespaceSchemaLocation=&quot;DivideProblem.xsd&quot;&gt;
        ///  &lt;ProblemType&gt;TSP&lt;/ProblemType&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///  &lt;Data&gt;
        ///    SWRlYWx5IHNhIGphayBnd2lhemR5IC0gbmllIG1vem5hIGljaCBvc2lhZ25hYywgYWxlIG1v
        ///    em5hIHNpZSBuaW1pIGtpZXJvd2FjLg0K
        ///  &lt;/Data&gt;
        ///  &lt;ComputationalNodes&gt;16&lt;/ComputationalNodes&gt;
        ///  &lt;NodeID&gt;8&lt;/NodeID&gt;
        ///&lt;/DivideProblem&gt;.
        /// </summary>
        internal static string DivideProblem {
            get {
                return ResourceManager.GetString("DivideProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Error xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///       xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///       xsi:noNamespaceSchemaLocation=&quot;Error.xsd&quot;&gt;
        ///  &lt;ErrorMessageType&gt;UnknownSender&lt;/ErrorMessageType&gt;
        ///&lt;/Error&gt;.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;NoOperation xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///             xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///             xsi:noNamespaceSchemaLocation=&quot;NoOperation.xsd&quot;&gt;
        ///  &lt;BackupCommunicationServers&gt;
        ///    &lt;BackupCommunicationServer address=&quot;192.168.100.1&quot; port=&quot;65535&quot; /&gt;
        ///  &lt;/BackupCommunicationServers&gt;
        ///&lt;/NoOperation&gt;.
        /// </summary>
        internal static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SolvePartialProblems xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///                      xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                      xsi:noNamespaceSchemaLocation=&quot;PartialProblems.xsd&quot;&gt;
        ///  &lt;ProblemType&gt;TSP&lt;/ProblemType&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///  &lt;CommonData&gt;
        ///    SWRlYWx5IHNhIGphayBnd2lhemR5IC0gbmllIG1vem5hIGljaCBvc2lhZ25hYywgYWxlIG1v
        ///    em5hIHNpZSBuaW1pIGtpZXJvd2FjLg0K
        ///  &lt;/CommonData&gt;
        ///  &lt;PartialProblems&gt;
        ///    &lt;PartialProblem&gt;
        ///      &lt;TaskId&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartialProblems {
            get {
                return ResourceManager.GetString("PartialProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Register xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///          xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:noNamespaceSchemaLocation=&quot;Register.xsd&quot;&gt;
        ///  &lt;Type&gt;TaskManager&lt;/Type&gt;
        ///  &lt;SolvableProblems&gt;
        ///    &lt;ProblemName&gt;TSP&lt;/ProblemName&gt;
        ///    &lt;ProblemName&gt;3-SAT&lt;/ProblemName&gt;
        ///    &lt;ProblemName&gt;DVRP&lt;/ProblemName&gt;
        ///    &lt;ProblemName&gt;GraphColoring&lt;/ProblemName&gt;
        ///  &lt;/SolvableProblems&gt;
        ///  &lt;ParallelThreads&gt;8&lt;/ParallelThreads&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///&lt;/Register&gt;.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;RegisterResponse xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///                  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                  xsi:noNamespaceSchemaLocation=&quot;RegisterResponse.xsd&quot;&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///  &lt;Timeout&gt;120&lt;/Timeout&gt;
        ///  &lt;BackupCommunicationServers&gt;
        ///    &lt;BackupCommunicationServer address=&quot;192.168.100.1&quot; port=&quot;65535&quot; /&gt;
        ///  &lt;/BackupCommunicationServers&gt;
        ///&lt;/RegisterResponse&gt;.
        /// </summary>
        internal static string RegisterResponse {
            get {
                return ResourceManager.GetString("RegisterResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SolutionRequest xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///                 xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                 xsi:noNamespaceSchemaLocation=&quot;SolutionRequest.xsd&quot;&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///&lt;/SolutionRequest&gt;.
        /// </summary>
        internal static string SolutionRequest {
            get {
                return ResourceManager.GetString("SolutionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Solutions xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///           xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///           xsi:noNamespaceSchemaLocation=&quot;Solution.xsd&quot;&gt;
        ///  &lt;ProblemType&gt;TSP&lt;/ProblemType&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///  &lt;CommonData&gt;
        ///    SWRlYWx5IHNhIGphayBnd2lhemR5IC0gbmllIG1vem5hIGljaCBvc2lhZ25hYywgYWxlIG1v
        ///    em5hIHNpZSBuaW1pIGtpZXJvd2FjLg0K
        ///  &lt;/CommonData&gt;
        ///  &lt;Solutions&gt;
        ///    &lt;Solution&gt;
        ///      &lt;TaskId&gt;123&lt;/TaskId&gt;
        ///      &lt;TimeoutOccured&gt;false&lt;/TimeoutOc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SolveRequest xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///              xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///              xsi:noNamespaceSchemaLocation=&quot;SolveRequest.xsd&quot;&gt;
        ///  &lt;ProblemType&gt;TSP&lt;/ProblemType&gt;
        ///  &lt;SolvingTimeout&gt;3600000&lt;/SolvingTimeout&gt;
        ///  &lt;Data&gt;
        ///    SWRlYWx5IHNhIGphayBnd2lhemR5IC0gbmllIG1vem5hIGljaCBvc2lhZ25hYywgYWxlIG1v
        ///    em5hIHNpZSBuaW1pIGtpZXJvd2FjLg0K
        ///  &lt;/Data&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///&lt;/SolveRequest&gt;.
        /// </summary>
        internal static string SolveRequest {
            get {
                return ResourceManager.GetString("SolveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SolveRequestResponse xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///                      xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                      xsi:noNamespaceSchemaLocation=&quot;SolveRequestResponse.xsd&quot;&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///&lt;/SolveRequestResponse&gt;.
        /// </summary>
        internal static string SolveRequestResponse {
            get {
                return ResourceManager.GetString("SolveRequestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Status xmlns=&quot;http://www.mini.pw.edu.pl/ucc/&quot;
        ///        xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///        xsi:noNamespaceSchemaLocation=&quot;Status.xsd&quot;&gt;
        ///  &lt;Id&gt;12&lt;/Id&gt;
        ///  &lt;Threads&gt;
        ///    &lt;Thread&gt;
        ///      &lt;State&gt;Idle&lt;/State&gt;
        ///    &lt;/Thread&gt;
        ///    &lt;Thread&gt;
        ///      &lt;State&gt;Idle&lt;/State&gt;
        ///    &lt;/Thread&gt;
        ///    &lt;Thread&gt;
        ///      &lt;State&gt;Busy&lt;/State&gt;
        ///      &lt;HowLong&gt;1244656&lt;/HowLong&gt;
        ///      &lt;ProblemInstanceId&gt;1212&lt;/ProblemInstanceId&gt;
        ///      &lt;TaskId&gt;123&lt;/TaskId&gt;
        ///      &lt;Probl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
